version: '3'
services:
    mysql:
        container_name: mysql
        image: mysql:8.0-debian
        restart: unless-stopped
        volumes:
          - ./mysql:/var/lib/mysql:delegated
        ports:
          - 3306:3306
        environment:
          TZ: 'America/Fortaleza'
          MYSQL_DATABASE: aula_mysql
          MYSQL_USER: aula_mysql
          MYSQL_PASSWORD: aula_mysql
          MYSQL_ROOT_PASSWORD: aula_mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: docker.io/bitnami/phpmyadmin:5
        ports:
          - 8010:8080
        environment:
          TZ: 'America/Fortaleza'
          DATABASE_HOST: mysql
          DATABASE_USER: root
          DATABASE_PASSWORD: aula_mysql
