version: '3'
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            TZ: 'America/Fortaleza'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

    phpmyadmin:
        container_name: phpmyadmin
        image: docker.io/bitnami/phpmyadmin:5
        ports:
          - 8010:8080
        environment:
          TZ: 'America/Fortaleza'
          DATABASE_HOST: 172.18.0.2
          DATABASE_USER: root
          DATABASE_PASSWORD: aula_mysql

volumes:
    mysql:
        driver: local
